apiVersion: v1
kind: ConfigMap
metadata:
  name: public-safety-lab-config
data:
  ASPNETCORE_ENVIRONMENT: Production
  Database__AutoMigrateOnStartup: "false"
  Authentication__AllowLegacyTenantHeader: "false"
