apiVersion: v1
kind: Secret
metadata:
  name: public-safety-lab-secrets
type: Opaque
# Do not put real credentials in this file.
# For production, replace this with External Secrets / CSI driver integration.
stringData:
  AwsResources__AccessKeyId: "<set-in-cluster>"
  AwsResources__SecretAccessKey: "<set-in-cluster>"
  AwsResources__PostgreSqlConnectionString: "Host=<postgres-host>;Port=5432;Database=public_safety_lab;Username=<db-user>;Password=<db-password>;Ssl Mode=Require;Trust Server Certificate=true"
  Authentication__ApiKeys__0__Key: "<set-in-cluster>"
  Authentication__ApiKeys__0__TenantId: demo
