apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: public-safety-lab
resources:
  - ../../base
  - postgres.yaml
  - localstack.yaml
patches:
  - path: configmap-patch.yaml
  - path: secret-patch.yaml
