apiVersion: v1
kind: Secret
metadata:
  name: public-safety-lab-secrets
stringData:
  AwsResources__AccessKeyId: test
  AwsResources__SecretAccessKey: test
  AwsResources__PostgreSqlConnectionString: Host=postgres;Port=5432;Database=public_safety_lab;Username=postgres;Password=postgres
  Authentication__ApiKeys__0__Key: demo-api-key
  Authentication__ApiKeys__0__TenantId: demo
